linux_setup_base_packages:
  apt:
    - htop
    - git
    - neovim
    - curl
    - wget
    - eza
    - fd-find
    - bat
    - ripgrep
    - jq
    - btop
    - duf
    - zoxide
    - fzf
    - tldr
    - httpie
    - trash-cli
    - lazygit
    - fish
  dnf:
    - htop
    - git
    - neovim
    - curl
    - wget
    - eza
    - ripgrep
    - jq
    - btop
    - duf
    - zoxide
    - fzf
    - tldr
    - lazygit
    - fish
  zypper:
    - htop
    - git
    - neovim
    - curl
    - wget
    - ripgrep
    - bat
    - jq
    - btop
    - duf
    - zoxide
    - fzf
    - lazygit
    - fish
  pacman:
    - htop
    - git
    - neovim
    - curl
    - wget
    - eza
    - fd
    - bat
    - ripgrep
    - jq
    - btop
    - duf
    - zoxide
    - fzf
    - tldr
    - httpie
    - trash-cli
    - lazygit
    - fish
