---
galaxy_info:
  role_name: fonts
  description: Install JetBrains Mono Nerd Font
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["all"]
    - name: Debian
      versions: ["all"]
    - name: ArchLinux
      versions: ["all"]
  galaxy_tags:
    - fonts
    - nerd-fonts
    - jetbrains

dependencies: []
