linux_setup_nvim_source: "{{ linux_setup_repo_root }}/config/nvim"
linux_setup_nvim_target: "{{ linux_setup_target_home }}/.config/nvim"
linux_setup_nvim_backup_suffix: ".backup.{{ ansible_date_time.epoch }}"
