linux_setup_fish_config_source: "{{ linux_setup_repo_root }}/config/fish"
linux_setup_fish_config_target: "{{ linux_setup_target_home }}/.config/fish"
linux_setup_fish_backup_suffix: ".backup.{{ ansible_date_time.epoch }}"
