---
galaxy_info:
  role_name: bash
  description: Deploy bash configuration files
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["all"]
    - name: Debian
      versions: ["all"]
    - name: ArchLinux
      versions: ["all"]
  galaxy_tags:
    - bash
    - shell
    - dotfiles

dependencies: []
