---
galaxy_info:
  role_name: desktop
  description: Configure desktop environment settings
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["all"]
    - name: Debian
      versions: ["all"]
  galaxy_tags:
    - desktop
    - gnome
    - gsettings

dependencies: []
